services:
  instagram-webhooks:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    command: ["python", "relatorio-alerta.py"]
    networks:
      - webhooks
    env_file:
      - stack.env