services:
  instagram-webhooks:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    # command: ["python", "main.py"]
    networks:
      - webhooks
    env_file:
      - stack.env
networks:
  webhooks:
    external: true