services:
  instagram-webhooks:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.12.3-alpine3.20
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install -r requirements.txt
        COPY main.py .
    restart: always
    # working_dir: /app
    volumes:
      # - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    command: ["python", "main.py"]
    networks:
      - webhooks
    env_file:
      - stack.env
    stdin_open: true 
    tty: true
networks:
  webhooks:
    external: true